In [17]:
import pandas as pd

d={'categories':['A','B','C','A'],'Values1':[20,30,40,50],'Values2':[50,60,70,60],'items':['sha','yas','meh','gou']}
df=pd.DataFrame(d)
df

  categories  Values1  Values2 items
0          A       20       50   sha
1          B       30       60   yas
2          C       40       70   meh
3          A       50       60   gou

In [ ]:
#multiple cloumns isused for agg in group by
test1=df.groupby(['categories','items']).agg({'Values1':'count','Values2':'sum'})  


test1

                  Values1  Values2
categories items
A          gou          1       60
           sha          1       50
B          yas          1       60
C          meh          1       70

In [ ]:
# single coulmn is used for group by
t=df.groupby(['categories','items'])['Values1'].sum()
t

categories  items
A           gou      50
            sha      20
B           yas      30
C           meh      40
Name: Values1, dtype: int64